import { TimeSlot } from "./types";

export const INITIAL_GURU = [
  "ABDUL RAHMAN BIN DAWAM",
  "ADILAH BINTI IJON",
  "AHMAD GHAZALI BIN SUFIAN",
  "AHMAD HAZIM BIN MUHAMAD",
  "AHMAD NAJIB BIN SHUKRI",
  "AMRAN BIN ARIFFIN",
  "BADRUL HISHAM BIN MAT RASHID",
  "CHE AZAHAR BIN CHE SOH",
  "FADZRELL QASYFIF BIN AHMAD RADZI",
  "FARAH FARIZA BINTI ESHA @ ISA",
  "FATIN SYAHIRAH BINTI MOHAMED IDRIS",
  "GUNAVATHY A/P KRISHNAN",
  "HANNAN HAYATI BINTI ABD.KAHAR",
  "HARFIDAH BINTI ARJAN",
  "HAZLINA BINTI ZAKARIA",
  "HIZANDIE BIN SHUAIB",
  "IMAN NURAINA BINTI ROSSLAN",
  "INTAN AIRUS RUSNIDA BINTI MOHD NOOR",
  "KHOO PHAU TZEN",
  "MADELYNE A/P PAUL",
  "MAISARA BINTI MD YON",
  "MAISARAH NADHIRAH BINTI ROSLI JAMIL",
  "MIOR MOHD FADZLI BIN MOHAMED YUSOF",
  "MOHD KHAIRUL NIZAM BIN MOHD ALIAS",
  "MOHD ZULKEFFLI BIN ZAINUDDIN",
  "MUHAMAD ANAS BIN AMRAN",
  "MUHAMAD QASSIM BIN GHAZALI",
  "MUHAMMAD AMIRUL AFIZI BIN OMAR",
  "MUHAMMAD JOSSHAIDY AMSYAR BIN JAFRI",
  "MUHAMMAD KHAIRULLOTHFI BIN MD KHAIR",
  "MUHAMMAD SYUKRAN BIN MUSTAFAR @ MOKHTAR",
  "NADHIRAH BINTI MOHAMAD",
  "NADIAH BINTI MOHD TAHIR",
  "NOO ANIZA BINTI SIDEK",
  "NOOR FATIENAH BINTI YAAKUB",
  "NOOR ZUZIHARIATI BINTI ZULKIFLI",
  "NOR ALIZAN BINTI HASAN",
  "NORAZILAH BINTI HASSAN",
  "NORIAMA BINTI OTHMAN",
  "NUR ATIKAH BINTI NAZLAN",
  "NUR NADIAH BINTI MOHD KHAIRUSALEH",
  "NUR SYAIDATUL AHTIRAH BINTI IBRAHIM",
  "NURAKMALIA BINTI KAMAL BAHRI",
  "NURUL DIYANA BINTI MOHD YUSOFF",
  "RAJA NORMAH BINTI RAJA HASSAN",
  "RANJITAH A/P RAMANATHAN",
  "ROSMAWATI BINTI ARBAIN",
  "RUSIDAH BINTI JUSOH",
  "SALIMAH FARHANAH BINTI SA'ARI",
  "SALMA BINTI ALI",
  "SAMSIAH BINTI MUSTAFFA @HAMZAH",
  "SHARIFAH BINTI KARIA",
  "SITI AISHAH BINTI ABDUL LATIFF",
  "SITI MARIAM BINTI IBRAHIM",
  "SITI NOR BINTI RAMLI",
  "SUHANA BINTI MANSOR",
  "SUZIANA BINTI MAHAMMAD",
  "SUZILA AZLINA BINTI YAHYA"
].sort();

export const TIMES: Record<string, TimeSlot[]> = {
  'T12': [ 
    {t:"07:30 - 08:30"}, {t:"08:30 - 09:30"}, {t:"09:30 - 10:00", r:1}, 
    {t:"10:00 - 11:00"}, {t:"11:00 - 12:00"}, {t:"12:00 - 13:00"}, 
    {t:"13:00 - 14:00"}, {t:"14:00 - 15:00"}, {t:"15:00 - 16:00"} 
  ],
  'T35': [ 
    {t:"07:30 - 08:30"}, {t:"08:30 - 09:30"}, {t:"09:30 - 10:30"}, 
    {t:"10:30 - 11:00", r:1}, {t:"11:00 - 12:00"}, {t:"12:00 - 13:00"}, 
    {t:"13:00 - 14:00"}, {t:"14:00 - 15:00"}, {t:"15:00 - 16:00"} 
  ]
};

export const DATA_KEY = 'pss_sys_v13';
export const BLOCK_KEY = 'pss_block_v13';
export const TEACH_KEY = 'pss_teach_v13';

export const ROOMS = ["Pusat Sumber Hamzani Suien", "Bilik Bacaan"];
